version: "3.8"

services:
  smart-amortizer:
    build: .
    container_name: smart-amortizer-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: smart-amortizer-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-docker.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl # Mount SSL certificates if you have them
    depends_on:
      - smart-amortizer
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
